# Generated by Django 5.2.14 on 2026-06-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('routing_intent', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mock_scenario', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('active_node', models.CharField(blank=True, max_length=64)),
                ('progress_message', models.TextField(blank=True)),
                ('analysis_plan_id', models.CharField(blank=True, max_length=64)),
                ('status_counts', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=32)),
                ('content', models.TextField(blank=True)),
                ('routing_intent', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDisplayResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_result_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('assistant_message', models.JSONField(blank=True, default=dict)),
                ('progress', models.JSONField(blank=True, default=list)),
                ('cards', models.JSONField(blank=True, default=list)),
                ('pending_questions', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('report_links', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_result', to='chatbot.analysisjob')),
            ],
            options={
                'db_table': 'analysis_display_results',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='chatbot.chatmessage'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('current_intent', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner_id', 'status'], name='chat_sessions_owner_status_idx')],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='chatbot.chatsession'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('report_type', models.CharField(choices=[('objection_draft', 'Objection draft'), ('fault_analysis', 'Fault analysis'), ('general', 'General')], default='objection_draft', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('storage_uri', models.CharField(blank=True, max_length=512)),
                ('content_summary', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('display_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.analysisdisplayresult')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.analysisjob')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('purpose', models.CharField(db_index=True, default='unknown', max_length=64)),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('storage_uri', models.CharField(blank=True, max_length=512)),
                ('privacy_risk', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('scanning', 'Scanning'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='uploaded', max_length=32)),
                ('scan_status', models.CharField(default='not_started', max_length=32)),
                ('agent_handoff', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('node_code', models.CharField(db_index=True, max_length=64)),
                ('node_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='success', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('structured_result', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('next_actions', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_results', to='chatbot.analysisjob')),
            ],
            options={
                'db_table': 'agent_results',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'node_code'], name='agent_results_job_node_idx'), models.Index(fields=['job', 'status'], name='agent_results_job_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=32)),
                ('active_node', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chatbot.analysisjob')),
            ],
            options={
                'db_table': 'analysis_job_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='ana_job_events_job_created_idx'), models.Index(fields=['status'], name='ana_job_events_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_msg_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['routing_intent'], name='chat_msg_routing_intent_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['owner_id', 'status'], name='analysis_jobs_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['session', 'status'], name='ana_jobs_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner_id', 'status'], name='reports_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['owner_id', 'session'], name='upl_files_owner_session_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['status', 'purpose'], name='upl_files_status_purpose_idx'),
        ),
    ]
