# Generated by Django 5.2.14 on 2026-06-29 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('expired', 'Expired')], db_index=True, default='active', max_length=32)),
                ('merge_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'guest_identities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentNodeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('node_name', models.CharField(max_length=200)),
                ('node_type', models.CharField(db_index=True, default='agent', max_length=64)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(db_index=True, default='planned', max_length=64)),
                ('contract_version', models.CharField(blank=True, max_length=64)),
                ('adapter_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agent_nodes',
                'ordering': ['node_code'],
                'indexes': [models.Index(fields=['status'], name='agent_nodes_status_idx'), models.Index(fields=['owner', 'status'], name='agent_nodes_owner_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('routing_intent', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quota_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='chatbot.chatsession')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='chatbot.guestidentity')),
            ],
            options={
                'db_table': 'ai_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invocation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('node_code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='queued', max_length=32)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('execution_mode', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('limitation_count', models.PositiveIntegerField(default=0)),
                ('retryable', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('quota_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invocations', to='chatbot.analysisjob')),
                ('agent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='chatbot.agentnodedefinition')),
                ('ai_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invocations', to='chatbot.aisession')),
            ],
            options={
                'db_table': 'agent_invocations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'code_groups',
                'ordering': ['group_code'],
                'indexes': [models.Index(fields=['is_active'], name='code_groups_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chatbot.codegroup')),
            ],
            options={
                'db_table': 'code_items',
                'ordering': ['group', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject_id', models.CharField(db_index=True, max_length=128)),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('quota_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usage_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['subject_id', 'scope'], name='usage_subject_scope_idx'), models.Index(fields=['quota_key'], name='usage_quota_key_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject_id', models.CharField(db_index=True, max_length=128)),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('limit_count', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'usage_quotas',
                'ordering': ['subject_id', 'scope'],
                'indexes': [models.Index(fields=['subject_id', 'scope'], name='quota_subject_scope_idx'), models.Index(fields=['reset_at'], name='quota_reset_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('auth_provider', models.CharField(blank=True, max_length=64)),
                ('provider_subject', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='users_status_idx'), models.Index(fields=['email'], name='users_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('plan_code', models.CharField(db_index=True, default='free', max_length=64)),
                ('status', models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], db_index=True, default='free', max_length=32)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='chatbot.useraccount')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='guestidentity',
            name='merged_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_guest_identities', to='chatbot.useraccount'),
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject_type', models.CharField(db_index=True, max_length=32)),
                ('subject_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=32)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_sessions', to='chatbot.guestidentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_sessions', to='chatbot.useraccount')),
            ],
            options={
                'db_table': 'auth_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chatbot.authsession')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='chatbot.guestidentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='chatbot.useraccount')),
            ],
            options={
                'db_table': 'auth_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='aisession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='chatbot.useraccount'),
        ),
        migrations.CreateModel(
            name='AgentFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('feedback_type', models.CharField(db_index=True, max_length=64)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='chatbot.agentresult')),
                ('invocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='chatbot.agentinvocation')),
            ],
            options={
                'db_table': 'agent_feedback_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['invocation', 'created_at'], name='agent_fb_inv_idx'), models.Index(fields=['feedback_type'], name='agent_fb_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentinvocation',
            index=models.Index(fields=['job', 'node_code'], name='agent_inv_job_node_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinvocation',
            index=models.Index(fields=['ai_session', 'status'], name='agent_inv_session_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinvocation',
            index=models.Index(fields=['status'], name='agent_inv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='codeitem',
            index=models.Index(fields=['group', 'is_active'], name='code_items_group_active_idx'),
        ),
        migrations.AddIndex(
            model_name='codeitem',
            index=models.Index(fields=['group', 'sort_order'], name='code_items_group_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='codeitem',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='code_items_group_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='sub_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_code', 'status'], name='sub_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='guestidentity',
            index=models.Index(fields=['status'], name='guest_status_idx'),
        ),
        migrations.AddIndex(
            model_name='guestidentity',
            index=models.Index(fields=['merged_user', 'status'], name='guest_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['subject_id', 'status'], name='auth_subject_status_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'status'], name='auth_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['subject_id', 'created_at'], name='auth_evt_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['event_type'], name='auth_evt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['owner_id', 'status'], name='ai_sess_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['session', 'status'], name='ai_sess_session_idx'),
        ),
    ]
