# Generated by Django 5.2.14 on 2026-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_guestidentity_agentnodedefinition_aisession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('event_version', models.CharField(default='history_event.v1', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_user_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('actor_guest_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('actor_auth_session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('actor_auth_state', models.CharField(blank=True, max_length=32)),
                ('subject_session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('subject_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('subject_job_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('subject_report_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source_surface', models.CharField(blank=True, max_length=64)),
                ('source_api_path', models.CharField(blank=True, db_index=True, max_length=256)),
                ('source_execution_mode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_node_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='success', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('subject', models.JSONField(blank=True, default=dict)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('privacy', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['subject_session_id', 'occurred_at'], name='hist_evt_session_time_idx'), models.Index(fields=['actor_user_id', 'occurred_at'], name='hist_evt_user_time_idx'), models.Index(fields=['actor_guest_id', 'occurred_at'], name='hist_evt_guest_time_idx'), models.Index(fields=['subject_job_id', 'event_type'], name='hist_evt_job_type_idx'), models.Index(fields=['event_type', 'status'], name='hist_evt_type_status_idx')],
            },
        ),
    ]
