# Generated by Django 5.2.14 on 2026-07-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_historyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_connections', to='chatbot.useraccount')),
            ],
            options={
                'db_table': 'oauth_connections',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['provider', 'revoked_at'], name='oauth_conn_provider_rev_idx'), models.Index(fields=['user', 'provider'], name='oauth_conn_user_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='oauth_connections_user_provider_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('provider_user_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='chatbot.useraccount')),
            ],
            options={
                'db_table': 'social_accounts',
                'ordering': ['-connected_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='soc_acc_user_provider_idx'), models.Index(fields=['email'], name='social_accounts_email_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='social_accounts_provider_user_uniq')],
            },
        ),
    ]
