# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_oauthconnection_socialaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_document_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("source_name", models.CharField(db_index=True, max_length=255)),
                ("jurisdiction", models.CharField(db_index=True, default="KR", max_length=50)),
                ("source_url", models.TextField(blank=True)),
                ("version_label", models.CharField(blank=True, max_length=120)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "source_documents",
                "ordering": ["source_name", "-effective_date", "source_document_id"],
                "indexes": [
                    models.Index(fields=["source_type", "status"], name="src_docs_type_status_idx"),
                    models.Index(fields=["jurisdiction", "status"], name="src_docs_juris_status_idx"),
                    models.Index(fields=["effective_date", "expire_date"], name="src_docs_temporal_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("source_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("source_type", models.CharField(db_index=True, max_length=50)),
                ("chunk_type", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("article_no", models.CharField(blank=True, db_index=True, max_length=50)),
                ("section_ref", models.CharField(blank=True, max_length=120)),
                ("content", models.TextField()),
                ("normalized_text", models.TextField(blank=True)),
                ("embedding_provider", models.CharField(blank=True, max_length=50)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("embedding_dimensions", models.PositiveIntegerField(blank=True, null=True)),
                ("embedding_vector", models.JSONField(blank=True, default=list)),
                ("is_searchable", models.BooleanField(db_index=True, default=True)),
                ("domain_tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunks",
                        to="chatbot.sourcedocument",
                    ),
                ),
            ],
            options={
                "db_table": "rag_chunks",
                "ordering": ["source_type", "source_id", "article_no", "chunk_id"],
                "indexes": [
                    models.Index(fields=["source_document", "is_searchable"], name="rag_chunks_doc_search_idx"),
                    models.Index(fields=["source_type", "chunk_type"], name="rag_chunks_type_chunk_idx"),
                    models.Index(fields=["source_type", "is_searchable"], name="rag_chunks_type_search_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetrievalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("retrieval_event_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("query_text", models.TextField(blank=True)),
                ("query_type", models.CharField(db_index=True, default="semantic", max_length=50)),
                ("top_k", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("source_refs", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_events",
                        to="chatbot.agentinvocation",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_events",
                        to="chatbot.analysisjob",
                    ),
                ),
            ],
            options={
                "db_table": "retrieval_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["job", "created_at"], name="retr_events_job_created_idx"),
                    models.Index(fields=["invocation", "created_at"], name="retr_events_inv_created_idx"),
                    models.Index(fields=["query_type"], name="retr_events_query_type_idx"),
                ],
            },
        ),
    ]
