# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_knowledge_rag_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentWorkItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_item_id", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("attempt_no", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=2)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, db_index=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ai_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="chatbot.aisession",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="chatbot.analysisjob",
                    ),
                ),
            ],
            options={
                "db_table": "agent_work_items",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "next_run_at"], name="agent_work_status_next_idx"),
                    models.Index(fields=["job", "status"], name="agent_work_job_status_idx"),
                    models.Index(fields=["ai_session", "status"], name="agent_work_ai_status_idx"),
                ],
            },
        ),
    ]
