# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_agent_work_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("fine_notice_objection", "Fine notice objection"),
                    ("fault_ratio_analysis", "Fault ratio analysis"),
                    ("objection_draft", "Objection draft"),
                    ("fault_analysis", "Fault analysis"),
                    ("general", "General"),
                ],
                default="objection_draft",
                max_length=64,
            ),
        ),
    ]
