# Generated by Django 6.0.6 on 2026-07-12 00:06

import hashlib

import django.db.models.deletion
from django.db import migrations, models


def backfill_authenticated_fault_cases(apps, schema_editor):
    case_model = apps.get_model("chatbot", "Case")
    session_model = apps.get_model("chatbot", "ChatSession")
    sessions = session_model.objects.filter(
        current_intent__in=["fault_ratio", "fault_ratio_text"],
    ).exclude(owner_id="")

    for session in sessions.iterator():
        digest = hashlib.sha256(session.session_id.encode("utf-8")).hexdigest()[:32]
        case, _created = case_model.objects.get_or_create(
            case_id=f"case_{digest}",
            defaults={
                "owner_id": session.owner_id,
                "title": session.title or "교통사고 과실 초기상담",
                "case_type": "accident_fault",
                "status": "ready",
                "metadata": {
                    "backfill_source": "authenticated_fault_ratio_session",
                    "source_session_id": session.session_id,
                },
            },
        )
        session.case_id = case.id
        session.save(update_fields=["case"])
        session.analysis_jobs.update(case_id=case.id)
        session.uploaded_files.update(case_id=case.id)
        session.reports.update(case_id=case.id)


def reverse_fault_case_backfill(apps, schema_editor):
    case_model = apps.get_model("chatbot", "Case")
    case_model.objects.filter(
        metadata__backfill_source="authenticated_fault_ratio_session",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_normalize_report_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='retention_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('fine_notice_objection', 'Fine notice objection'), ('fault_ratio_analysis', 'Fault ratio analysis'), ('general', 'General'), ('initial_consultation', 'Initial consultation'), ('expert_handoff', 'Expert handoff')], default='fine_notice_objection', max_length=64),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('owner_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('case_type', models.CharField(db_index=True, default='accident_fault', max_length=64)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('awaiting_fact_confirmation', 'Awaiting fact confirmation'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('needs_input', 'Needs input'), ('ready', 'Ready'), ('high_risk_handoff', 'High risk handoff'), ('closed', 'Closed'), ('deleted', 'Deleted')], db_index=True, default='intake', max_length=40)),
                ('risk_level', models.CharField(db_index=True, default='standard', max_length=32)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('current_fact_version', models.PositiveIntegerField(default=0)),
                ('current_report_version', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner_id', 'status'], name='cases_owner_status_idx'), models.Index(fields=['case_type', 'status'], name='cases_type_status_idx')],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='chatbot.case'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='chatbot.case'),
        ),
        migrations.AddField(
            model_name='report',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.case'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='chatbot.case'),
        ),
        migrations.RunPython(backfill_authenticated_fault_cases, reverse_fault_case_backfill),
        migrations.CreateModel(
            name='ConfirmedFactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact_version_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(db_index=True, default='confirmed', max_length=32)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('user_edit_history', models.JSONField(blank=True, default=list)),
                ('confirmed_by', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_versions', to='chatbot.case')),
            ],
            options={
                'db_table': 'confirmed_fact_versions',
                'ordering': ['case', '-version_no'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='source_fact_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chatbot.confirmedfactversion'),
        ),
        migrations.AddConstraint(
            model_name='confirmedfactversion',
            constraint=models.UniqueConstraint(fields=('case', 'version_no'), name='confirmed_fact_case_version_uniq'),
        ),
    ]
